#!/bin/bash
tmpfile=$(mktemp 2>/dev/null) || tmpfile="/tmp/test$(date +%N)"
tmplog=$(mktemp 2>/dev/null) || tmplog="/tmp/test$(date +%N)"
trap "rm -f $tmpfile $tmplog" 0 1 2 5 15

sed -i 's/^#http/http/g' /etc/apk/repositories
apk update > /dev/null

echo "starting desktop installation" >> ${LOG}

# xorg
setup-xorg-base >>${LOG} 2>&1
Xorg -configure >>${LOG} 2>&1
mv /root/xorg.conf.new /etc/X11/xorg.conf
# extra video
apk add mesa-dri-swrast >>${LOG} 2>&1

(apk add terraos-desktop >>${tmplog} 2>&1 &)

counter=0
(
    while true; do
cat <<EOF
XXX
$counter

Installing $package...
XXX
EOF
        # check for OK to exit
        grep -e "^OK:" $tmplog > /dev/null
        if [ $? -eq 0 ]; then
            sleep 3
            exit 0
        fi
        cur_file=$(tail -1 $tmplog)
        # only update status on package progress; skip actions
        echo $cur_file | grep -e "^(" >/dev/null
        if [ $? -ne 0 ]; then
            continue
        fi
        package=$(echo $cur_file | cut -d' ' -f3)
        cur_item=$(echo $cur_file | cut -d'/' -f1 | tr -d '(')
        total_items=$(echo $cur_file | cut -d'/' -f2 | cut -d' ' -f1 | tr -d ')')
        counter=$(printf "%.0f" $(bc<<<"scale=1; $cur_item/$total_items * 100"))
        sleep 0.5
    done
) | dialog --backtitle "$APP_TITLE" --title "Desktop Installation" --gauge "Please wait..." 10 70 0

echo "installation complete" >> ${LOG}
